# Generated by Django 3.1.1 on 2020-09-20 04:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200919_0416'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitante',
            name='data',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitante',
            name='limit',
            field=models.FloatField(default=0, verbose_name='Limite'),
        ),
        migrations.AlterField(
            model_name='solicitante',
            name='renda',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='solicitante',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
