# Generated by Django 3.1.1 on 2020-09-20 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200920_0425'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitante',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
