# Generated by Django 3.1.1 on 2020-09-24 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_solicitante_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitante',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='nome'),
        ),
    ]
