# Generated by Django 3.1.1 on 2020-09-25 02:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200924_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitante',
            name='data',
        ),
        migrations.RemoveField(
            model_name='solicitante',
            name='status',
        ),
        migrations.AddField(
            model_name='solicitante',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='solicitante',
            name='atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='solicitante',
            name='criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
